# Generated by Django 4.1.1 on 2022-10-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('calories', models.IntegerField()),
                ('proteins', models.IntegerField()),
                ('fats', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
            ],
        ),
    ]
