# Generated by Django 4.1.1 on 2022-10-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dish',
            new_name='Ingredient',
        ),
    ]
