# Generated by Django 4.1.1 on 2022-10-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0002_rename_dish_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('time', models.CharField(choices=[('M', 'morning'), ('A', 'afternoon'), ('E', 'evening')], db_index=True, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_weigth', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eat.ingredient')),
                ('meal_title', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eat.mealtitle')),
            ],
        ),
    ]
