# Generated by Django 4.1.1 on 2022-10-26 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diet.ingredient', verbose_name='ingredient'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diet.mealname', verbose_name='meal_name'),
        ),
    ]
