# Generated by Django 4.1.3 on 2022-11-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='target',
            field=models.CharField(choices=[('L', 'LOSE'), ('S', 'STABLE'), ('G', 'GAIN')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
