# Generated by Django 4.1.3 on 2022-11-13 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_alter_user_height_alter_user_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='meal_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diet.mealplan'),
        ),
    ]
