# Generated by Django 4.1.3 on 2022-11-17 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='gen_meals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diet.generatedmeals'),
        ),
    ]
